<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: DevOps with Liberty, Maven, and Chef (Part 1)</title>
	<atom:link href="https://developer.ibm.com/wasdev/docs/devops-liberty-maven-chef-part-1/feed/" rel="self" type="application/rss+xml" />
	<link>https://developer.ibm.com/wasdev/docs/devops-liberty-maven-chef-part-1/</link>
	<description>Enterprise Java developer community</description>
	<lastBuildDate>Mon, 02 Dec 2019 09:24:19 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.9.9</generator>
	<item>
		<title>By: dinesh</title>
		<link>https://developer.ibm.com/wasdev/docs/devops-liberty-maven-chef-part-1/#comment-147039</link>
		<dc:creator><![CDATA[dinesh]]></dc:creator>
		<pubDate>Sun, 24 Jul 2016 09:44:59 +0000</pubDate>
		<guid isPermaLink="false">https://developer.ibm.com/wasdev/?post_type=doc&#038;p=8846#comment-147039</guid>
		<description><![CDATA[I am getting the below error while doing a login

err] 	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:837)
[err] 	at [internal classes]
[err] 	at com.acmeair.jpa.service.CustomerServiceImpl.getCustomerByUsername(CustomerServiceImpl.java:94)
[err] 	at com.acmeair.jpa.service.CustomerServiceImpl.validateCustomer(CustomerServiceImpl.java:101)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[err] 	at java.lang.reflect.Method.invoke(Method.java:498)
[err] 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
[err] 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:196)
[err] 	at com.sun.proxy.$Proxy47.validateCustomer(Unknown Source)
[err] 	at com.acmeair.web.LoginREST.login(LoginREST.java:41)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[err] 	at java.lang.reflect.Method.invoke(Method.java:498)
[err] 	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:636)
[err] 	at [internal classes]
[err] 	at com.acmeair.web.RESTCookieSessionFilter.doFilter(RESTCookieSessionFilter.java:63)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)
[err] 	at [internal classes]
[err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[err] 	at java.lang.Thread.run(Thread.java:745)
[err] Caused by: java.lang.NoClassDefFoundError: org/eclipse/persistence/transaction/JTASynchronizationListener
[err] 	at org.eclipse.persistence.transaction.JTATransactionController.(JTATransactionController.java:65)
[err] 	at [internal classes]
[err] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[err] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[err] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[err] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[err] 	at java.lang.Class.newInstance(Class.java:442)
[err] 	at org.eclipse.persistence.internal.security.PrivilegedAccessHelper.newInstanceFromClass(PrivilegedAccessHelper.java:428)
[err] 	at [internal classes]
[err] 	... 72 more]]></description>
		<content:encoded><![CDATA[<p>I am getting the below error while doing a login</p>
<p>err] 	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:837)<br />
[err] 	at [internal classes]<br />
[err] 	at com.acmeair.jpa.service.CustomerServiceImpl.getCustomerByUsername(CustomerServiceImpl.java:94)<br />
[err] 	at com.acmeair.jpa.service.CustomerServiceImpl.validateCustomer(CustomerServiceImpl.java:101)<br />
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
[err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
[err] 	at java.lang.reflect.Method.invoke(Method.java:498)<br />
[err] 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)<br />
[err] 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:196)<br />
[err] 	at com.sun.proxy.$Proxy47.validateCustomer(Unknown Source)<br />
[err] 	at com.acmeair.web.LoginREST.login(LoginREST.java:41)<br />
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br />
[err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
[err] 	at java.lang.reflect.Method.invoke(Method.java:498)<br />
[err] 	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:636)<br />
[err] 	at [internal classes]<br />
[err] 	at com.acmeair.web.RESTCookieSessionFilter.doFilter(RESTCookieSessionFilter.java:63)<br />
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)<br />
[err] 	at [internal classes]<br />
[err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)<br />
[err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)<br />
[err] 	at java.lang.Thread.run(Thread.java:745)<br />
[err] Caused by: java.lang.NoClassDefFoundError: org/eclipse/persistence/transaction/JTASynchronizationListener<br />
[err] 	at org.eclipse.persistence.transaction.JTATransactionController.(JTATransactionController.java:65)<br />
[err] 	at [internal classes]<br />
[err] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br />
[err] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)<br />
[err] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br />
[err] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)<br />
[err] 	at java.lang.Class.newInstance(Class.java:442)<br />
[err] 	at org.eclipse.persistence.internal.security.PrivilegedAccessHelper.newInstanceFromClass(PrivilegedAccessHelper.java:428)<br />
[err] 	at [internal classes]<br />
[err] 	&#8230; 72 more</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Jagan</title>
		<link>https://developer.ibm.com/wasdev/docs/devops-liberty-maven-chef-part-1/#comment-19689</link>
		<dc:creator><![CDATA[Jagan]]></dc:creator>
		<pubDate>Fri, 01 Aug 2014 15:37:35 +0000</pubDate>
		<guid isPermaLink="false">https://developer.ibm.com/wasdev/?post_type=doc&#038;p=8846#comment-19689</guid>
		<description><![CDATA[Great set of articles.   Would be great if you could add a pictorial view of what is being accomplished in the article in part 1.   Kind of like a devOPS pipeline.   Thanks.]]></description>
		<content:encoded><![CDATA[<p>Great set of articles.   Would be great if you could add a pictorial view of what is being accomplished in the article in part 1.   Kind of like a devOPS pipeline.   Thanks.</p>
]]></content:encoded>
	</item>
</channel>
</rss>
